name:                yampa-openal
version:             0.1.0.0
github:              "githubuser/yampa-alut"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/yampa-alut#readme>

dependencies:
- base >= 4.7 && < 5
- Yampa
- OpenAL
- ALUT
- linear
- StateVar
- containers
- ObjectName
- tree-diff
- async

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  yampa-alut-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yampa-openal
    - random
