name:                Yampa-OpenAL
version:             0.1.0.1
github:              "vitalibarozzi/yampa-openal"
license:             BSD-3-Clause
author:              "J. V. Vitali Barozzi"
maintainer:          "vitalivitor@gmail.com"
copyright:           "2024 J. V. Vitali Barozzi"

description:         Adapter between Yampa and OpenAL.

dependencies:
- base >= 4.7 && < 5
- Yampa
- OpenAL
- ALUT
- containers
- linear
- StateVar
- ObjectName
- simple-affine-space
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  generated-other-modules: Paths_Yampa_OpenAL

tests:
  yampa-alut-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Yampa-OpenAL
    - random
